services:
  client:
    build:
      context: ./client # Path to your client folder
      dockerfile: Dockerfile # Your client Dockerfile
    ports:
      - "5173:80" # HOST:CONTAINER
    depends_on:
      - server
    environment:
      # URL where your backend API is accessible FROM THE CLIENT
      - VITE_API_URL=http://localhost:5000 # <-- PUT YOUR BACKEND URL HERE
    networks:
      - mern

  server:
    build:
      context: ./server # Path to your server folder
      dockerfile: Dockerfile # Your server Dockerfile
    ports:
      - "5000:5000" # Backend port
    environment:
      - PORT=${PORT}
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - mern

networks:
  mern:

volumes:
  mongo_data:
