services:
  client:
    image: hassaan28/mern-auth-client:latest
    ports:
      - "80:80" # Expose client on port 80 (standard HTTP)
    depends_on:
      - server
    restart: always
    networks:
      - mern

  server:
    image: hassaan28/mern-auth-server:latest
    ports:
      - "5000:5000" # Expose backend API
    environment:
      - PORT=5000
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    restart: always
    networks:
      - mern

networks:
  mern:
    driver: bridge
